[package]
name = "ydk-parser"
version = "0.1.0"
edition = "2021"
default-run = "print_deck"

[workspace]

[[bin]]
name = "print_deck"
path = "src/bin/print.rs"

[dependencies]
serde_json = "1.0"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }

